version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - echo Building the App
      - yarn run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend'
