name: Deploy Frontend to AWS CodeDeploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install-aws-cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
      - run: aws --version
        shell: bash
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      - name: Copy Source
        uses: actions/checkout@v4
        with:
          ref: main
      - name: yarn install
        run: yarn install
        working-directory: frontend
      - name: yarn run next-lint
        run: yarn run next-lint
        working-directory: frontend
      - name: yarn run prettier-lint
        run: yarn run prettier-lint
        working-directory: frontend
      - name: yarn run build
        run: yarn run build
        working-directory: frontend
      - name: zip "${{ github.run_id }}-${{ github.sha }}.zip"
        run: zip -r --quiet "${{ github.run_id }}-${{ github.sha }}.zip" .
        shell: bash
      - name: aws configure
        run: >-
          aws configure set aws_access_key_id ${{ secrets.AWS_SECRET_ID }};
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }};
          aws configure set default.region eu-central-1;
        shell: bash
      - name: Waiting for the deployments that in progress to end
        run: >-
          while [ "$( aws deploy list-deployments --application-name frontend --deployment-group-name frontend --include-only-statuses Queued InProgress | jq -r '.deployments')" != "[]" ]; do
            echo -e "Waiting for the deployments that in progress to end. Sleeping 60 seconds";
            sleep 60s;
          done;
        shell: bash
      - name: aws s3 cp
        run: >-
          aws s3 cp ${{ github.run_id }}-${{ github.sha }}.zip
          "s3://${{ secrets.AWS_CODE_DEPLOY_BUCKET }}/frontend-build/${{ github.run_id }}-${{ github.sha }}.zip"
        shell: bash
      - name: aws deploy create-deployment
        run: >-
          aws deploy create-deployment
          --application-name frontend
          --deployment-group-name frontend
          --description "$${{ github.ref_name }} - ${{ github.sha }}"
          --s3-location bucket=${{ secrets.AWS_CODE_DEPLOY_BUCKET }},key=frontend-build/${{ github.run_id }}-${{ github.sha }}.zip,bundleType=zip
        shell: bash
      - name: aws deploy register-application-revision
        run: >-
          aws deploy register-application-revision
          --application-name frontend
          --description "$${{ github.ref_name }} - ${{ github.sha }}"
          --s3-location bucket=${{ secrets.AWS_CODE_DEPLOY_BUCKET }},key=frontend-build/${{ github.run_id }}-${{ github.sha }}.zip,bundleType=zip
        shell: bash
