name: Deploy Frontend to AWS ECS

on:
  push:
    branches: ["feature/ecs"]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      - name: Copy Source
        uses: actions/checkout@v4
        with:
          ref: main
      - name: yarn install
        run: yarn install
        working-directory: ./frontend
      - name: yarn run next-lint
        run: yarn run next-lint
        working-directory: ./frontend
      - name: yarn run prettier-lint
        run: yarn run prettier-lint
        working-directory: ./frontend
      - name: yarn run build
        run: yarn run build
        working-directory: ./frontend
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
          IMAGE_TAG: frontend
        run: |
          pwd
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
